# Cleaning Employee Exit Surveys

In this lab, you'll clean exit surveys from employees of the [Department of Education, Training and Employment (DETE)](https://en.wikipedia.org/wiki/Department_of_Education_and_Training_(Queensland)}) and the Technical and Further Education (TAFE) body of the Queensland government in Australia. The TAFE exit survey can be found [here](https://data.gov.au/dataset/ds-qld-89970a3b-182b-41ea-aea2-6f9f17b5907e/details?q=exit%20survey) and the survey for the DETE can be found [here](https://data.gov.au/dataset/ds-qld-fe96ff30-d157-4a81-851d-215f2a0fe26d/details?q=exit%20survey).

Complete the tasks listed below. You can submit the completed lab until 11:59 PM in the night.

<u>Requirement:</u><br>
Do your best to write Pythonic code instead of the traditional programming code.

<u>Hint:</u><br>
For all of these tasks, you would need to read the data first using __pd.read_csv__

### Task 1 (2 marks)

Import the necessary libraries, read the data __dete_survey.csv__ as well as __tafe_survey.csv__, and ensure that the columns are not truncated (that is, by default pandas shows only the first few columns followed by ellipsis followed by the last few columns).

<u>Hint:</u> pd.options...

Once you have done that, output some information about your columns such as how many columns are there, the data types of the columns etc.

In [33]:
### Write your code below this comment.
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
dete = pd.read_csv('data/dete_survey.csv')
tafe = pd.read_csv('data/tafe_survey.csv')
print('There are', dete.shape[0], 'rows and', dete.shape[1], 'columns in the DETE dataframe. \n')
print('Column Names and Types in DETE:\n', dete.dtypes)

There are 822 rows and 56 columns in the DETE dataframe.

Column Names and Types in DETE:
 ID                                      int64
SeparationType                         object
Cease Date                             object
DETE Start Date                        object
Role Start Date                        object
Position                               object
Classification                         object
Region                                 object
Business Unit                          object
Employment Status                      object
Career move to public sector             bool
Career move to private sector            bool
Interpersonal conflicts                  bool
Job dissatisfaction                      bool
Dissatisfaction with the department      bool
Physical work environment                bool
Lack of recognition                      bool
Lack of job security                     bool
Work location                            bool
Employment conditions                    bool
Maternity/family                         bool
Relocation                               bool
Study/Travel                             bool
Ill Health                               bool
Traumatic incident                       bool
Work life balance                        bool
Workload                                 bool
None of the above                        bool
Professional Development               object
Opportunities for promotion            object
Staff morale                           object
Workplace issue                        object
Physical environment                   object
Worklife balance                       object
Stress and pressure support            object
Performance of supervisor              object
Peer support                           object
Initiative                             object
Skills                                 object
Coach                                  object
Career Aspirations                     object
Feedback                               object
Further PD                             object
Communication                          object
My say                                 object
Information                            object
Kept informed                          object
Wellness programs                      object
Health & Safety                        object
Gender                                 object
Age                                    object
Aboriginal                             object
Torres Strait                          object
South Sea                              object
Disability                             object
NESB                                   object
dtype: object

In [32]:
print('There are', tafe.shape[0], 'rows and', tafe.shape[1], 'columns in the TAFE dataframe. \n')
print('Column Names and Types in TAFE:\n', tafe.dtypes)

There are 702 rows and 72 columns in the TAFE dataframe.

Column Names and Types in TAFE:
 Record ID                                                                                                                                                        float64
Institute                                                                                                                                                         object
WorkArea                                                                                                                                                          object
CESSATION YEAR                                                                                                                                                   float64
Reason for ceasing employment                                                                                                                                     object
Contributing Factors. Career Move - Public Sector                                                                                                                 object
Contributing Factors. Career Move - Private Sector                                                                                                                object
Contributing Factors. Career Move - Self-employment                                                                                                               object
Contributing Factors. Ill Health                                                                                                                                  object
Contributing Factors. Maternity/Family                                                                                                                            object
Contributing Factors. Dissatisfaction                                                                                                                             object
Contributing Factors. Job Dissatisfaction                                                                                                                         object
Contributing Factors. Interpersonal Conflict                                                                                                                      object
Contributing Factors. Study                                                                                                                                       object
Contributing Factors. Travel                                                                                                                                      object
Contributing Factors. Other                                                                                                                                       object
Contributing Factors. NONE                                                                                                                                        object
Main Factor. Which of these was the main factor for leaving?                                                                                                      object
InstituteViews. Topic:1. I feel the senior leadership had a clear vision and direction                                                                            object
InstituteViews. Topic:2. I was given access to skills training to help me do my job better                                                                        object
InstituteViews. Topic:3. I was given adequate opportunities for personal development                                                                              object
InstituteViews. Topic:4. I was given adequate opportunities for promotion within %Institute]Q25LBL%                                                               object
InstituteViews. Topic:5. I felt the salary for the job was right for the responsibilities I had                                                                   object
InstituteViews. Topic:6. The organisation recognised when staff did good work                                                                                     object
InstituteViews. Topic:7. Management was generally supportive of me                                                                                                object
InstituteViews. Topic:8. Management was generally supportive of my team                                                                                           object
InstituteViews. Topic:9. I was kept informed of the changes in the organisation which would affect me                                                             object
InstituteViews. Topic:10. Staff morale was positive within the Institute                                                                                          object
InstituteViews. Topic:11. If I had a workplace issue it was dealt with quickly                                                                                    object
InstituteViews. Topic:12. If I had a workplace issue it was dealt with efficiently                                                                                object
InstituteViews. Topic:13. If I had a workplace issue it was dealt with discreetly                                                                                 object
WorkUnitViews. Topic:14. I was satisfied with the quality of the management and supervision within my work unit                                                   object
WorkUnitViews. Topic:15. I worked well with my colleagues                                                                                                         object
WorkUnitViews. Topic:16. My job was challenging and interesting                                                                                                   object
WorkUnitViews. Topic:17. I was encouraged to use my initiative in the course of my work                                                                           object
WorkUnitViews. Topic:18. I had sufficient contact with other people in my job                                                                                     object
WorkUnitViews. Topic:19. I was given adequate support and co-operation by my peers to enable me to do my job                                                      object
WorkUnitViews. Topic:20. I was able to use the full range of my skills in my job                                                                                  object
WorkUnitViews. Topic:21. I was able to use the full range of my abilities in my job. ; Category:Level of Agreement; Question:YOUR VIEWS ABOUT YOUR WORK UNIT]     object
WorkUnitViews. Topic:22. I was able to use the full range of my knowledge in my job                                                                               object
WorkUnitViews. Topic:23. My job provided sufficient variety                                                                                                       object
WorkUnitViews. Topic:24. I was able to cope with the level of stress and pressure in my job                                                                       object
WorkUnitViews. Topic:25. My job allowed me to balance the demands of work and family to my satisfaction                                                           object
WorkUnitViews. Topic:26. My supervisor gave me adequate personal recognition and feedback on my performance                                                       object
WorkUnitViews. Topic:27. My working environment was satisfactory e.g. sufficient space, good lighting, suitable seating and working area                          object
WorkUnitViews. Topic:28. I was given the opportunity to mentor and coach others in order for me to pass on my skills and knowledge prior to my cessation date     object
WorkUnitViews. Topic:29. There was adequate communication between staff in my unit                                                                                object
WorkUnitViews. Topic:30. Staff morale was positive within my work unit                                                                                            object
Induction. Did you undertake Workplace Induction?                                                                                                                 object
InductionInfo. Topic:Did you undertake a Corporate Induction?                                                                                                     object
InductionInfo. Topic:Did you undertake a Institute Induction?                                                                                                     object
InductionInfo. Topic: Did you undertake Team Induction?                                                                                                           object
InductionInfo. Face to Face Topic:Did you undertake a Corporate Induction; Category:How it was conducted?                                                         object
InductionInfo. On-line Topic:Did you undertake a Corporate Induction; Category:How it was conducted?                                                              object
InductionInfo. Induction Manual Topic:Did you undertake a Corporate Induction?                                                                                    object
InductionInfo. Face to Face Topic:Did you undertake a Institute Induction?                                                                                        object
InductionInfo. On-line Topic:Did you undertake a Institute Induction?                                                                                             object
InductionInfo. Induction Manual Topic:Did you undertake a Institute Induction?                                                                                    object
InductionInfo. Face to Face Topic: Did you undertake Team Induction; Category?                                                                                    object
InductionInfo. On-line Topic: Did you undertake Team Induction?process you undertook and how it was conducted.]                                                   object
InductionInfo. Induction Manual Topic: Did you undertake Team Induction?                                                                                          object
Workplace. Topic:Did you and your Manager develop a Performance and Professional Development Plan (PPDP)?                                                         object
Workplace. Topic:Does your workplace promote a work culture free from all forms of unlawful discrimination?                                                       object
Workplace. Topic:Does your workplace promote and practice the principles of employment equity?                                                                    object
Workplace. Topic:Does your workplace value the diversity of its employees?                                                                                        object
Workplace. Topic:Would you recommend the Institute as an employer to others?                                                                                      object
Gender. What is your Gender?                                                                                                                                      object
CurrentAge. Current Age                                                                                                                                           object
Employment Type. Employment Type                                                                                                                                  object
Classification. Classification                                                                                                                                    object
LengthofServiceOverall. Overall Length of Service at Institute (in years)                                                                                         object
LengthofServiceCurrent. Length of Service at current workplace (in years)                                                                                         object
dtype: object

### Task 2 (1 mark)

You should be able to make the following observation based on the work you did above in Task 1:
  - The __dete_survey__ dataframe contains `'Not Stated'` values that indicate values are missing, but they aren't represented as `NaN`.
  
Read the dataset __dete_survey.csv__ again such that the `'Not Stated'` values are replaced with NaN ensuring that the mechanism for representing missing values is consistent across the dataset.

<u>Hint:</u> Use the __na_values__ argument in __pd.read_csv__

In [35]:
### Write your code below this comment.
dete = pd.read_csv('data/dete_survey.csv', na_values ='Not Stated')

,ID,SeparationType,Cease Date,DETE Start Date,Role Start Date,Position,Classification,Region,Business Unit,Employment Status,Career move to public sector,Career move to private sector,Interpersonal conflicts,Job dissatisfaction,Dissatisfaction with the department,Physical work environment,Lack of recognition,Lack of job security,Work location,Employment conditions,Maternity/family,Relocation,Study/Travel,Ill Health,Traumatic incident,Work life balance,Workload,None of the above,Professional Development,Opportunities for promotion,Staff morale,Workplace issue,Physical environment,Worklife balance,Stress and pressure support,Performance of supervisor,Peer support,Initiative,Skills,Coach,Career Aspirations,Feedback,Further PD,Communication,My say,Information,Kept informed,Wellness programs,Health & Safety,Gender,Age,Aboriginal,Torres Strait,South Sea,Disability,NESB
0,1,Ill Health Retirement,08/2012,1984.0,2004.0,Public Servant,A01-A04,Central Office,Corporate Strategy and Peformance,Permanent Full-time,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,True,A,A,N,N,N,A,A,A,A,N,N,N,A,A,A,N,A,A,N,N,N,Male,56-60,NaN,NaN,NaN,NaN,Yes
1,2,Voluntary Early Retirement (VER),08/2012,NaN,NaN,Public Servant,AO5-AO7,Central Office,Corporate Strategy and Peformance,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,A,A,N,N,N,N,A,A,A,N,N,N,A,A,A,N,A,A,N,N,N,Male,56-60,NaN,NaN,NaN,NaN,NaN
2,3,Voluntary Early Retirement (VER),05/2012,2011.0,2011.0,Schools Officer,NaN,Central Office,Education Queensland,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,A,A,N,N,N,N,Male,61 or older,NaN,NaN,NaN,NaN,NaN
3,4,Resignation-Other reasons,05/2012,2005.0,2006.0,Teacher,Primary,Central Queensland,NaN,Permanent Full-time,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,A,N,N,N,A,A,N,N,A,A,A,A,A,A,A,A,A,A,A,N,A,Female,36-40,NaN,NaN,NaN,NaN,NaN
4,5,Age Retirement,05/2012,1970.0,1989.0,Head of Curriculum/Head of Special Education,NaN,South East,NaN,Permanent Full-time,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,A,A,N,N,D,D,N,A,A,A,A,A,A,SA,SA,D,D,A,N,A,M,Female,61 or older,NaN,NaN,NaN,NaN,NaN

### Task 3 (1 mark)

Both the __dete_survey__ and __tafe_survey__ contain many columns that we don't need to complete our analysis.

Drop columns 28-48 (inclusive of both ends) in __dete_survey__  as well as columns 17-65 in __tafe_survey__ and save the resulting dataframes as __dete_survey_updated__ and __tafe_survey_updated__ respectively. Also confirm that the number of columns in the new dataframes is less by 21 and 49 respectively compared with the original dataframes.

In [64]:
### Write your code below this comment.
dete_survey_updated = dete.drop(dete.columns[28:49], axis=1)
tafe_survey_updated = tafe.drop(tafe.columns[17:66], axis=1)
print("The number of columns is less by", len(dete.columns)-len(dete_survey_updated.columns), 
      "in the new DETE dataframe. \n")
print("The number of columns is less by", len(tafe.columns)-len(tafe_survey_updated.columns), 
      "in the new TAFE dataframe.")

The number of columns is less by 21 in the new DETE dataframe.

The number of columns is less by 49 in the new TAFE dataframe.

### Task 4 (2 marks)

Rename all the columns in the dataframe __dete_survey_updated__ such that the following requirements are satisfied:

1. The column names are in lower case
2. Any leading and trailing spaces are removed from column names
3. Any space in column names is replaced with an underscore ( _ )

Also, rename the columns in the dataframe __tafe_survey_updated__ such that they match the names in __dete_survey_updated__. You can use the following dictionary for mapping:

    {'Record ID': 'id', 'CESSATION YEAR': 'cease_date', 'Reason for ceasing employment': 'separationtype', 
    'Gender. What is your Gender?': 'gender', 'CurrentAge. Current Age': 'age', 
    'Employment Type. Employment Type': 'employment_status', 'Classification. Classification': 'position',
    'LengthofServiceOverall. Overall Length of Service at Institute (in years)': 'institute_service', 
    'LengthofServiceCurrent. Length of Service at current workplace (in years)': 'role_service'}

In [65]:
### Write your code below this comment.
dete_survey_updated.columns = dete_survey_updated.columns.str.strip().str.lower().str.replace(" ", "_")
tafe_survey_updated.rename(columns={'Record ID': 'id', 'CESSATION YEAR': 'cease_date', 'Reason for ceasing employment': 'separationtype', 
'Gender. What is your Gender?': 'gender', 'CurrentAge. Current Age': 'age', 
'Employment Type. Employment Type': 'employment_status', 'Classification. Classification': 'position',
'LengthofServiceOverall. Overall Length of Service at Institute (in years)': 'institute_service', 
'LengthofServiceCurrent. Length of Service at current workplace (in years)': 'role_service'}, inplace=True)

### Task 5 (2 marks)

Get the number of unique values in the ```'separationtype'``` column of both the dataframes __tafe_survey_updated__ and __dete_survey_updated__. You may notice that there is a single value with the name 'Resignation' in __tafe_survey_updated__ while there are multiple values including the word 'Resignation' in __dete_survey_updated__.

Update the ```'separationtype'``` column in __dete_survey_updated__ such that any value that contains the word 'Resignation' is replaced with 'Resignation'. For example, 'Resignation-Other reasons' should be replaced with 'Resignation' etc.

<u>Hint:</u> All values that include the word 'Resignation' also include a hyphen (-). You can use this fact to quickly update the values.

Once you have done that, create two new updated dataframes __dete_resignations__ and __tafe_resignations__ which copy the dataframes __dete_survey_updated__ and __tafe_survey_updated__ respectively with the condition that the ```'separationtype'``` column in both the source dataframes equals the value 'Resignation'.

In [66]:
### Write your code below this comment.
print('Unique separation types TAFE: \n', tafe_survey_updated['separationtype'].unique(), '\n')
print('There are', len(tafe_survey_updated['separationtype'].unique()), 
      'unique separation types in the TAFE dataframe. \n')
print('Unique separation types DETE: \n', dete_survey_updated['separationtype'].unique(), '\n')
print('There are', len(dete_survey_updated['separationtype'].unique()), 
      'unique separation types in the DETE dataframe.')

Unique separation types TAFE:
 ['Contract Expired' 'Retirement' 'Resignation' 'Retrenchment/ Redundancy'
 'Termination' 'Transfer' nan]

There are 7 unique separation types in the TAFE dataframe.

Unique separation types DETE:
 ['Ill Health Retirement' 'Voluntary Early Retirement (VER)'
 'Resignation-Other reasons' 'Age Retirement' 'Resignation-Other employer'
 'Resignation-Move overseas/interstate' 'Other' 'Contract Expired'
 'Termination']

There are 9 unique separation types in the DETE dataframe.

In [67]:
dete_survey_updated.separationtype = dete_survey_updated.separationtype.apply(lambda x: 'Resignation' if 'Resignation' in x else x)
dete_resignations = dete_survey_updated[dete_survey_updated['separationtype']=='Resignation']
tafe_resignations = tafe_survey_updated[tafe_survey_updated['separationtype']=='Resignation']

### Task 6 (2 marks)

Show the counts of missing values for all the columns in the __tafe_resignations__ dataframe. 

Now go ahead and first store the counts of all the unique values (including missing values) for the ```'employment_status'``` column in a variable named __es_cnts__ and then show the counts. Once you have done that, fill the missing values for the ```'employment_status'``` column using the most frequent non-NA unique value. Finally, show the counts of all the unique values (including missing values) for the ```'employment_status'``` column once again. There shouldn't be any missing values for this column now.

<u>Hint:</u> Use _idxmax()_

In [78]:
### Write your code below this comment.
print('Number of missing values per column in tafe_resignations: \n \n', tafe_resignations.isna().sum(), '\n')

es_cnts = tafe_resignations['employment_status'].value_counts(dropna=False)
print('Unique values in employment_status: \n \n', es_cnts)

Number of missing values per column in tafe_resignations:

 id                                                      0
Institute                                               0
WorkArea                                                0
cease_date                                              5
separationtype                                          0
Contributing Factors. Career Move - Public Sector       8
Contributing Factors. Career Move - Private Sector      8
Contributing Factors. Career Move - Self-employment     8
Contributing Factors. Ill Health                        8
Contributing Factors. Maternity/Family                  8
Contributing Factors. Dissatisfaction                   8
Contributing Factors. Job Dissatisfaction               8
Contributing Factors. Interpersonal Conflict            8
Contributing Factors. Study                             8
Contributing Factors. Travel                            8
Contributing Factors. Other                             8
Contributing Factors. NONE                              8
gender                                                 50
age                                                    50
employment_status                                      50
position                                               50
institute_service                                      50
role_service                                           50
dtype: int64

Unique values in employment_status:

 Temporary Full-time    111
Permanent Full-time     98
NaN                     50
Contract/casual         29
Temporary Part-time     27
Permanent Part-time     25
Name: employment_status, dtype: int64

dtype('int64')

In [82]:
tafe_resignations['employment_status'].fillna(es_cnts.idxmax(), inplace=True)
es_cnts_no_na = tafe_resignations['employment_status'].value_counts(dropna=False)
print('Unique values in employment_status with NA filled: \n \n', es_cnts_no_na)

Unique values in employment_status with NA filled:

 Temporary Full-time    161
Permanent Full-time     98
Contract/casual         29
Temporary Part-time     27
Permanent Part-time     25
Name: employment_status, dtype: int64

/var/folders/bz/4718vpys5hn6s49pgws_hng40000gn/T/ipykernel_21312/1280875680.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tafe_resignations['employment_status'].fillna(es_cnts.idxmax(), inplace=True)